import BingoCard from "../components/bingoGame/BingoCard";
import HistoryContainer from "../features/history/HistoryContainer";

const savedPatterns = [
  {
    theme: "#967c9b",
    pattern: [
      { index: 0, value: 1, checked: true },
      { index: 1, value: 7, checked: true },
      { index: 2, value: 13, checked: true },
      { index: 3, value: 19, checked: true },
      { index: 4, value: 25, checked: true },
      { index: 5, value: 2, checked: false },
      { index: 6, value: 8, checked: false },
      { index: 7, value: 14, checked: false },
      { index: 8, value: 20, checked: false },
      { index: 9, value: 21, checked: false },
      { index: 10, value: 3, checked: false },
      { index: 11, value: 9, checked: false },
      { index: 12, value: 15, checked: false },
      { index: 13, value: 16, checked: false },
      { index: 14, value: 22, checked: false },
      { index: 15, value: 4, checked: false },
      { index: 16, value: 10, checked: false },
      { index: 17, value: 11, checked: false },
      { index: 18, value: 17, checked: false },
      { index: 19, value: 23, checked: false },
      { index: 20, value: 5, checked: false },
      { index: 21, value: 6, checked: false },
      { index: 22, value: 12, checked: false },
      { index: 23, value: 18, checked: false },
      { index: 24, value: 24, checked: false },
    ],
  },

  {
    theme: "#4b255e",
    pattern: [
      { index: 0, value: 17, checked: true },
      { index: 1, value: 4, checked: true },
      { index: 2, value: 22, checked: false },
      { index: 3, value: 9, checked: true },
      { index: 4, value: 1, checked: false },
      { index: 5, value: 14, checked: true },
      { index: 6, value: 25, checked: true },
      { index: 7, value: 6, checked: false },
      { index: 8, value: 18, checked: false },
      { index: 9, value: 11, checked: true },
      { index: 10, value: 3, checked: false },
      { index: 11, value: 20, checked: true },
      { index: 12, value: 8, checked: false },
      { index: 13, value: 15, checked: true },
      { index: 14, value: 24, checked: false },
      { index: 15, value: 7, checked: false },
      { index: 16, value: 13, checked: true },
      { index: 17, value: 2, checked: false },
      { index: 18, value: 21, checked: false },
      { index: 19, value: 10, checked: true },
      { index: 20, value: 23, checked: false },
      { index: 21, value: 5, checked: true },
      { index: 22, value: 16, checked: false },
      { index: 23, value: 12, checked: false },
      { index: 24, value: 19, checked: false },
    ],
  },

  {
    theme: "#1f5a65",
    pattern: [
      { index: 0, value: 8, checked: false },
      { index: 1, value: 21, checked: true },
      { index: 2, value: 3, checked: true },
      { index: 3, value: 16, checked: false },
      { index: 4, value: 24, checked: false },
      { index: 5, value: 12, checked: false },
      { index: 6, value: 5, checked: true },
      { index: 7, value: 19, checked: false },
      { index: 8, value: 7, checked: true },
      { index: 9, value: 14, checked: false },
      { index: 10, value: 25, checked: true },
      { index: 11, value: 1, checked: false },
      { index: 12, value: 18, checked: true },
      { index: 13, value: 10, checked: false },
      { index: 14, value: 6, checked: true },
      { index: 15, value: 22, checked: false },
      { index: 16, value: 13, checked: true },
      { index: 17, value: 4, checked: false },
      { index: 18, value: 20, checked: false },
      { index: 19, value: 9, checked: true },
      { index: 20, value: 15, checked: false },
      { index: 21, value: 2, checked: false },
      { index: 22, value: 11, checked: true },
      { index: 23, value: 23, checked: false },
      { index: 24, value: 17, checked: true },
    ],
  },

  {
    theme: "#491a1a",
    pattern: [
      { index: 0, value: 23, checked: true },
      { index: 1, value: 11, checked: true },
      { index: 2, value: 5, checked: true },
      { index: 3, value: 19, checked: true },
      { index: 4, value: 2, checked: true },
      { index: 5, value: 16, checked: false },
      { index: 6, value: 8, checked: false },
      { index: 7, value: 24, checked: false },
      { index: 8, value: 13, checked: false },
      { index: 9, value: 6, checked: false },
      { index: 10, value: 21, checked: false },
      { index: 11, value: 4, checked: false },
      { index: 12, value: 17, checked: false },
      { index: 13, value: 9, checked: false },
      { index: 14, value: 1, checked: false },
      { index: 15, value: 12, checked: false },
      { index: 16, value: 25, checked: false },
      { index: 17, value: 7, checked: false },
      { index: 18, value: 15, checked: false },
      { index: 19, value: 3, checked: false },
      { index: 20, value: 18, checked: false },
      { index: 21, value: 10, checked: false },
      { index: 22, value: 22, checked: false },
      { index: 23, value: 14, checked: false },
      { index: 24, value: 20, checked: false },
    ],
  },

  {
    theme: "#3a3e19",
    pattern: [
      { index: 0, value: 6, checked: true },
      { index: 1, value: 18, checked: false },
      { index: 2, value: 24, checked: true },
      { index: 3, value: 11, checked: false },
      { index: 4, value: 3, checked: true },
      { index: 5, value: 20, checked: false },
      { index: 6, value: 15, checked: true },
      { index: 7, value: 9, checked: false },
      { index: 8, value: 1, checked: true },
      { index: 9, value: 22, checked: false },
      { index: 10, value: 13, checked: false },
      { index: 11, value: 5, checked: true },
      { index: 12, value: 17, checked: false },
      { index: 13, value: 25, checked: true },
      { index: 14, value: 8, checked: false },
      { index: 15, value: 2, checked: false },
      { index: 16, value: 14, checked: true },
      { index: 17, value: 21, checked: false },
      { index: 18, value: 7, checked: false },
      { index: 19, value: 19, checked: true },
      { index: 20, value: 10, checked: false },
      { index: 21, value: 23, checked: false },
      { index: 22, value: 4, checked: true },
      { index: 23, value: 16, checked: false },
      { index: 24, value: 12, checked: false },
    ],
  },
];

function History() {
  return (
    <div className="text-white">
      <h4>You have won 3 out of 5 games </h4>
      <div className="flex gap-7 mt-7 flex-col"></div>
      <HistoryContainer />
    </div>
  );
}

export default History;
